spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/gitrdfdb}
    username: root
    password: ${SPRING_DATASOURCE_PASSWORD:example} # temporary for prototyping
  servlet:
    multipart:
      max-file-size: 2GB
      max-request-size: 2GB

server:
  port: 8080

springdoc:
  api-docs:
    path: /listener-service/api-docs
  swagger-ui:
    path: /listener-service/swagger


logging:
  level:
    org.hibernate.SQL: DEBUG 
    root: info
    de:
      leipzig:
        htwk:
          gitrdf:
            listener: debug
