spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/gitrdfdb
    username: root
    password: example # temporary for prototyping
  servlet:
    multipart:
      max-file-size: 2GB
      max-request-size: 2GB

server:
  port: 8080